# Generated by Django 6.0.7 on 2026-09-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('RECEPTIONIST', 'Receptionist'), ('PATIENT', 'Patient')], max_length=20),
        ),
    ]
