# Generated by Django 6.0.7 on 2026-08-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
